tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'sanemat/font'

brew 'ack'
brew 'cmake'
#brew 'connect'
brew 'coreutils'
brew 'ctags'
brew 'git'
brew 'ghq'
brew 'htop-osx'
brew 'libevent'
brew 'libyaml'
brew 'lua'
brew 'lua@5.1'
brew 'lv'
brew 'mercurial'
brew 'pidof'
brew 'pstree'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'tmux'
brew 'tree'
brew 'vim', args: ['HEAD', 'with-lua', 'with-python3']
brew 'wget'
brew 'plenv'
brew 'pyenv'
brew 'goenv'
brew 'exenv'
brew 'nodenv'
brew 'direnv'
brew 'mysql'
brew 'asciinema'

cask_args appdir: '/Applications'
#cask 'google-chrome'
#cask 'firefox'
#cask 'hyper'
#cask 'slack'
#cask 'skype'
#cask 'jasper'
#cask 'Karabiner-Elements'
#cask 'marp'
#cask 'notion'
#cask 'zoomus'
#cask 'visual-studio-code'
#cask 'kindle'
#cask 'Dropbox'

# fonts
#tap  'homebrew/cask-fonts'
#cask 'font-hack-nerd-font'
