#!/bin/sh
cd $(dirname $0)

mkdir -p $HOME/.config/nvim
mkdir -p $HOME/.config/pet

ln -s $PWD/zshrc           $HOME/.zshrc
ln -s $PWD/vimrc           $HOME/.vimrc
ln -s $PWD/vim             $HOME/.vim
ln -s $PWD/gitconfig       $HOME/.gitconfig
ln -s $PWD/gitmessage      $HOME/.gitmessage
ln -s $PWD/gitignore       $HOME/.gitignore
ln -s $PWD/tmux.conf       $HOME/.tmux.conf
ln -s $PWD/editorconfig    $HOME/.editorconfig
ln -s $PWD/editorconfig    $HOME/src/.editorconfig
ln -s $PWD/textlintrc      $HOME/.textlintrc
ln -s $PWD/proverc         $HOME/.proverc
ln -s $PWD/gemrc           $HOME/.gemrc
ln -s $PWD/Brewfile        $HOME/Brewfile
ln -s $PWD/tool-versions   $HOME/.tool-versions

ln -s $PWD/vimrc                    $HOME/.config/nvim/init.vim
ln -s $PWD/config/pet/snippet.toml  $HOME/.config/pet/snippet.toml

