#!/bin/sh
cd $(dirname $0)

ln -s $PWD/zshrc           $HOME/.zshrc
ln -s $PWD/zsh             $HOME/.zsh
ln -s $PWD/vim             $HOME/.vim
ln -s $PWD/gitconfig       $HOME/.gitconfig
ln -s $PWD/gitmessage      $HOME/.gitmessage
ln -s $PWD/gitignore       $HOME/.gitignore
ln -s $PWD/tmux.conf       $HOME/.tmux.conf
ln -s $PWD/textlintrc      $HOME/.textlintrc
ln -s $PWD/proverc         $HOME/.proverc
ln -s $PWD/Brewfile        $HOME/Brewfile
ln -s $PWD/tool-versions   $HOME/.tool-versions
ln -s $PWD/default-perl-modules $HOME/.default-perl-modules

mkdir -p $HOME/.config
ln -s $PWD/config/nvim $HOME/.config/nvim
ln -s $PWD/config/pet $HOME/.config/pet
ln -s $PWD/config/efm-langserver $HOME/.config/efm-langserver
ln -s $PWD/config/perlimports $HOME/.config/perlimports

