version: 2
root-markers:
  - .git/

# FOR DEBUG
log-file: /tmp/efm-langserver-output.log
log-level: 3

tools:
  textlint: &textlint
    lint-command: 'npx textlint --format unix --preset ja-technical-writing ${INPUT}'
    lint-formats:
      - '%f:%l:%n: %m'

  eslint: &eslint
    lint-command: 'npx eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

  graphql-schema-linter: &graphql-schema-linter
    lint-command: 'npx graphql-schema-linter --format compact'
    lint-formats:
      - '%f:%l:%c %m'
    lint-after-open: true


languages:
  markdown:
    - <<: *textlint
  javascript:
    - <<: *eslint
  graphql:
    - <<: *eslint
    - <<: *graphql-schema-linter

